name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Le pipeline se déclenche lorsqu'on pousse du code sur 'main'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Tests
        run: echo "Ici, tu peux ajouter des tests unitaires avec pytest"

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t nassimkhal/projet1-flask:latest .

      - name: Push to Docker Hub
        run: docker push nassimkhal/projet1-flask:latest
